import type { SetupStep, DlpProfile, CategoryLabel } from "./types";

export const SETUP_STEPS: SetupStep[] = [
  {
    id: "discovery-profile",
    num: 1,
    title: "Discovery Profile",
    sub: "Choose which DLP profiles classify your data across the estate.",
    eyebrow: "Tenant-wide setting",
    time: "~3 min",
    required: true,
    route: "discovery-profile",
  },
  {
    id: "scanners",
    num: 2,
    title: "Scanner Deployment",
    sub: "Deploy in-network scanners so data can be classified without leaving your perimeter.",
    eyebrow: "In-network scanning",
    time: "~10 min",
    required: false,
    optional: true,
    whenToSkip:
      "Skip if you’re comfortable with scans running from the tenant cloud, or if you only have SaaS apps to connect.",
    route: "scanners",
  },
  {
    id: "csp",
    num: 3,
    title: "Onboard Cloud Provider",
    sub: "Connect AWS, Azure, GCP, or OCI to auto-discover and monitor your data stores.",
    eyebrow: "Cloud connection",
    time: "~8 min",
    required: false,
    optional: true,
    whenToSkip:
      "Skip if you only have SaaS apps or on-prem stores, or if you want to connect specific data stores manually without enumerating a whole cloud account.",
    route: "csp",
  },
  {
    id: "data-store",
    num: 4,
    title: "Connect Data Stores",
    sub: "Connect specific cloud, on-prem, and SaaS data stores and configure their scan settings.",
    eyebrow: "Data store setup",
    time: "~5 min per store",
    required: true,
    route: "data-store",
  },
  {
    id: "scan",
    num: 5,
    title: "Monitor Scan Progress",
    sub: "Confirm your first scans are healthy and learn how to diagnose issues.",
    eyebrow: "Scan visibility",
    time: "~2 min",
    required: false,
    route: "scan",
  },
  {
    id: "overview",
    num: 6,
    title: "Overview Dashboard Tour",
    sub: "Walk through the data security posture and risk graph once your first scan completes.",
    eyebrow: "Dashboard tour",
    time: "~3 min",
    required: false,
    route: "overview-tour",
  },
];

export const DLP_PROFILES: DlpProfile[] = [
  { id: "dlp-pii", name: "DLP-PII", kind: "predefined", cats: ["PII"], desc: "Personally Identifiable Information including names, SSNs, government IDs and contact details.", defaultOn: true },
  { id: "dlp-pci", name: "DLP-PCI", kind: "predefined", cats: ["PCI"], desc: "Payment Card Industry data: PAN, expiry, CVV, magnetic stripe.", defaultOn: true },
  { id: "dlp-phi", name: "DLP-PHI", kind: "predefined", cats: ["PHI"], desc: "Protected Health Information including diagnoses, prescriptions, HIPAA-regulated identifiers.", defaultOn: true },
  { id: "dlp-spii", name: "DLP-SPII", kind: "predefined", cats: ["SPII", "PII"], desc: "Sensitive PII: passport, driver license, biometric and immigration identifiers." },
  { id: "dlp-gdpr", name: "DLP-GDPR", kind: "predefined", cats: ["PII", "SPII"], desc: "EU GDPR-classified personal data and special-category information." },
  { id: "dlp-ccpa", name: "DLP-CCPA", kind: "predefined", cats: ["PII"], desc: "California Consumer Privacy Act regulated data points." },
  { id: "dlp-ferpa", name: "DLP-FERPA", kind: "predefined", cats: ["PII"], desc: "Student educational records protected under FERPA." },
  { id: "dlp-glba", name: "DLP-GLBA", kind: "predefined", cats: ["PFI", "PII"], desc: "Gramm-Leach-Bliley Act-protected financial information." },
  { id: "dlp-sox", name: "DLP-SOX-Financials", kind: "predefined", cats: ["PFI", "BII"], desc: "Sarbanes-Oxley regulated financial records, balance sheets, internal controls." },
  { id: "dlp-pfi", name: "DLP-PFI", kind: "predefined", cats: ["PFI"], desc: "Personal Financial Information: account numbers, IBAN, routing, balances." },
  { id: "dlp-pai", name: "DLP-PAI", kind: "predefined", cats: ["PAI"], desc: "Personal Authentication Information: passwords, security questions, MFA seeds." },
  { id: "dlp-bii", name: "DLP-BII", kind: "predefined", cats: ["BII"], desc: "Business Identifiable Information: contracts, internal financials, M&A docs." },
  { id: "dlp-psi", name: "DLP-PSI", kind: "predefined", cats: ["PSI"], desc: "Personal Sentiment Information: HR notes, performance reviews, complaints." },
  { id: "dlp-aws-keys", name: "DLP-Cleartext-AWS-Keys", kind: "predefined", cats: ["Cred", "PAI"], desc: "AWS access key IDs, secret access keys and session tokens in plaintext." },
  { id: "dlp-gcp-keys", name: "DLP-Cleartext-GCP-Keys", kind: "predefined", cats: ["Cred", "PAI"], desc: "GCP service-account JSON keys and OAuth client secrets." },
  { id: "dlp-azure-creds", name: "DLP-Cleartext-Azure-Secrets", kind: "predefined", cats: ["Cred", "PAI"], desc: "Azure shared access signatures and connection strings." },
  { id: "dlp-api-tokens", name: "DLP-API-Tokens", kind: "predefined", cats: ["Cred"], desc: "API tokens for common SaaS providers (Stripe, Slack, GitHub, Datadog, …)." },
  { id: "dlp-private-keys", name: "DLP-Private-Keys", kind: "predefined", cats: ["Cred"], desc: "PEM, OpenSSH and PGP private keys in repos or shared drives." },
  { id: "dlp-source-code", name: "DLP-Source-Code", kind: "predefined", cats: ["Code", "BII"], desc: "Heuristic match for source code files in unmanaged storage." },
  { id: "dlp-secrets", name: "DLP-Generic-Secrets", kind: "predefined", cats: ["Cred"], desc: "High-entropy strings, JWTs, bearer tokens of unknown origin." },
  { id: "dlp-hipaa-extras", name: "DLP-HIPAA-Identifiers", kind: "predefined", cats: ["PHI", "SPII"], desc: "18 HIPAA-defined identifiers beyond core PHI." },
  { id: "dlp-icd10", name: "DLP-ICD-10-Codes", kind: "predefined", cats: ["PHI"], desc: "International Classification of Diseases (ICD-10) clinical codes." },
  { id: "dlp-mrn", name: "DLP-Medical-Record-Nums", kind: "predefined", cats: ["PHI", "SPII"], desc: "Medical Record Numbers (MRN) and patient identifiers." },
  { id: "dlp-uk-nino", name: "DLP-UK-National-Insurance", kind: "predefined", cats: ["PII"], desc: "UK National Insurance numbers." },
  { id: "dlp-au-tfn", name: "DLP-Australia-TFN", kind: "predefined", cats: ["PII"], desc: "Australian Tax File Numbers." },
  { id: "dlp-india-aadhaar", name: "DLP-India-Aadhaar", kind: "predefined", cats: ["PII", "SPII"], desc: "Indian Aadhaar 12-digit unique identification numbers." },
  { id: "dlp-eu-iban", name: "DLP-EU-IBAN", kind: "predefined", cats: ["PFI"], desc: "International Bank Account Numbers across SEPA." },
  { id: "dlp-japan-mynumber", name: "DLP-Japan-MyNumber", kind: "predefined", cats: ["PII"], desc: "Japan personal social security identifiers." },
  { id: "dlp-canada-sin", name: "DLP-Canada-SIN", kind: "predefined", cats: ["PII"], desc: "Canadian Social Insurance Numbers." },
  { id: "custom-acme-customer", name: "Acme-Customer-IDs", kind: "custom", cats: ["PII", "BII"], desc: "Custom regex for internal customer ID format (ACM-XXXXXXX)." },
  { id: "custom-pricing", name: "Confidential-Pricing-Sheets", kind: "custom", cats: ["BII"], desc: "Filename + content dictionary for FY26 pricing materials." },
  { id: "custom-ma", name: "Project-Polaris-M&A", kind: "custom", cats: ["BII"], desc: "Sensitive M&A workstream keywords, codenames and party names." },
  { id: "custom-eng-roadmap", name: "Engineering-Roadmap", kind: "custom", cats: ["BII"], desc: "Custom dictionary covering codenames in the eng planning workspace." },
  { id: "custom-board", name: "Board-Materials", kind: "custom", cats: ["BII", "PFI"], desc: "Board deck templates, redline contracts, comp letters." },
];

export const CATEGORY_LABELS: Record<string, CategoryLabel> = {
  PII: { label: "PII", cls: "cat-pii", full: "Personally Identifiable Information" },
  SPII: { label: "SPII", cls: "cat-spii", full: "Sensitive PII" },
  PCI: { label: "PCI", cls: "cat-pci", full: "Payment Card Industry" },
  PHI: { label: "PHI", cls: "cat-phi", full: "Protected Health Info" },
  PAI: { label: "PAI", cls: "cat-pai", full: "Personal Authentication Info" },
  PFI: { label: "PFI", cls: "cat-pfi", full: "Personal Financial Info" },
  PSI: { label: "PSI", cls: "cat-psi", full: "Personal Sentiment Info" },
  BII: { label: "BII", cls: "cat-bii", full: "Business Identifiable Info" },
  Code: { label: "Code", cls: "cat-code", full: "Source Code" },
  Cred: { label: "Cred", cls: "cat-cred", full: "Credentials & Secrets" },
};

export const ALL_CATEGORIES = Object.keys(CATEGORY_LABELS);

export const PLACEHOLDER_COPY: Record<string, { title: string; summary: string; bullets: string[] }> = {
  overview: {
    title: "Overview Dashboard Tour",
    summary: "Walk through the data security posture and risk graph once your first scan completes.",
    bullets: [
      "Critical Risks summary with severity breakdown",
      "Sensitive Data Findings for stored and transferred data",
      "Identity coverage across user groups",
      "Managed vs unmanaged data store breakdown",
    ],
  },
};
